command: ["uvicorn", "data_extraction_app.backend.app:app", "--workers", "2"]
env:
  - name: WAREHOUSE_ID
    value: 4615730c28d25332
  - name: JOB_ID
    value: 349315058243638
  - name: VOLUME_PATH
    value: /Volumes/nikks_fevm_workspace_7405607030687545/test_repo_merve/productmanuals/
  - name: AI_EXTRACT_PROCESSED_TABLE
    value: nikks_fevm_workspace_7405607030687545.test_repo_merve.test_productmanuals_processed"
  - name: AGENT_ENDPOINT
    value: mas-2e9b5c23-endpoint