command: ["uvicorn", "data_extraction_app.backend.app:app", "--workers", "2"]
env:
  - name: WAREHOUSE_ID
    value: "<SQL_WAREHOUSE_ID>"
  - name: JOB_ID
    value: "<JOB_ID>"
  - name: VOLUME_PATH
    value: "/Volumes/<CATALOG>/<SCHEMA>/<VOLUME_NAME>"
  - name: AI_EXTRACT_PROCESSED_TABLE
    value: "<CATALOG>.<SCHEMA>.<TABLE_PREFIX>_productmanuals_processed"
  - name: AGENT_ENDPOINT
    value: "<SUPERVISOR_AGENT_ENDPOINT_NAME>"